### ISSUE TITLE
My own templates are overwritten

### ISSUE THREAD

**Issue by raphaelgoetter** [JeffryBooher/brackets-newproject-extension#33]
Hello,

I use my own templates in the user templates folder, but each times the "New Project" Extension is updated, they systematically are overwritten by the default templates from the plugin.

How can I avoid this ?

**Comment by JeffryBooher** [comment]
This was fixed with #14 and documented in the repo's `readme.md`.  Feel free to amend it in a PR if you want to add more to the discussion. thanks!
