### ISSUE TITLE
Custom Templates ?

### ISSUE THREAD

**Issue by SheepDomination** [JeffryBooher/brackets-newproject-extension#46]
How can I create a custom template from a HTML file, with MQ etc ?

**Comment by JeffryBooher** [comment]
The extension has support for a user templates folder. Create the folder  `BracketsProjectTemplates` in your `Documents` folder (Mac: `~/Documents`, Windows: `%HOMEPATH%\Documents`) You can also point it to another location by editing Brackets' preferences file and adding `BracketsNewProjectExtension.userTemplatesFolder: <folder>`.

**Comment by JeffryBooher** [comment]
Then Create new folders in the `BracketsProjectTemplates` for each template you want to create and add the template contents to those folders.  They will show up in the dialog.

**Comment by SheepDomination** [comment]
You mean the config.json file ?

**Comment by SheepDomination** [comment]
Hi, I have the paths created, how do I save my template so I can select it if I want; or edit it when loading or starting a new project ?

**Comment by JeffryBooher** [comment]
you can save it anywhere and just copy the folder into your `BracketsProjectTemplates` folder and it should just show up.

**Comment by JeffryBooher** [comment]
I'm going to treat this as a feature request. Seems like a good one to have.

**Comment by SheepDomination** [comment]
Feature Request ? What did I say :-) ?
